spring:
  datasource:
    username: root
    password: Lcx0618.
    url: jdbc:mysql://localhost:3306/myself?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
  show-actuator: true